openapi: "3.0.0"
info:
  title: "checkers API"
  description: "api for checkers online"
  version: "0.1.1.0"
servers:
  - url: http://127.0.0.1/
paths:
  /auth/register/:
    post:
      parameters: 
        - $ref: '#/components/parameters/login'
        - $ref: '#/components/parameters/password'
      responses:
        200:
          description: пользователь успешно зарегистрирован
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/token'
  /auth/login/:
    post:
      parameters: 
        - $ref: '#/components/parameters/login'
        - $ref: '#/components/parameters/password'
      responses:
        404:
          description: Wrong login or password
          content:
            application/json:
              schema:
                description: todo
            
  #/auth/register/:
components:
  parameters:
    login:
      name: login
      in: query
      schema:
        type: string
    password:
      name: password
      in: query
      schema:
        type: string
      
  schemas:
    token:
      description: "authentication token"
      properties:
        token:
          type: string
    user_data:
      description: nn
      properties:
        bio:
          description: user's biograhy
          type: string
          example: >
            multiline user's
            
            biography
        birth_date:
          type: string
          example: '2000-11-16'
          format: '%4d-%2d-%2d'
        location:
          type: string
          example: Somewhere
        name:
          type: string
          example: Some Name
